---
title: "EDA"
author: "qntkhvn"
output:
  html_document:
    code_folding: show
    df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, 
                      warning = FALSE,
                      comment = "",
                      fig.height = 5,
                      fig.width = 6,
                      fig.align = "center")
```

# Set up

```{r}
library(tidyverse)
library(janitor)
library(scales)
library(lubridate)
theme_set(theme_light()) 

library(here)
path <- "Desktop/consulting/project"
load(here(path, "consulting_data.RData"))
load(here(path, "location_data.RData"))
# load(here(path, "nbhd_map.RData"))

geo_cleaned <- read_csv("https://www.dropbox.com/s/9jcsk1477qc4k60/geo_cleaned.csv?dl=1") %>% 
  mutate(prop_id = as.character(prop_id),
         zip = as.character(zip))
```

# Data wrangling

```{r}
# cleaning by column order
housing <- final %>%
  clean_names() %>%
  mutate(
    
    prop_id = as.character(prop_id),
    
    bld_type = str_remove(bld_type, ".*- "),
    
    appraiser = str_sub(appraiser, start = 7),
    
    nbhd = str_sub(nbhd, 1, 4),
    
    qual = ifelse(str_detect(qual, "M"), NA, str_remove(qual, " -.*")),
  
    cond = str_remove(cond, ".*- "),
    
    kitchen_rating = str_remove(kitchen_rating, ".*- "),
    kitchen_rating = ifelse(kitchen_ct == 0, NA, kitchen_rating),
    
    
    full_bath_ct = ifelse(is.na(full_bath_ct), 0, full_bath_ct),
    full_bath_rating = str_remove(full_bath_rating, ".*- "),
    full_bath_rating = ifelse(full_bath_ct == 0, NA, full_bath_rating),
    
    half_bath_ct = ifelse(is.na(half_bath_ct), 0, half_bath_ct),
    half_bath_rating = str_remove(half_bath_rating, ".*- "),
    half_bath_rating = ifelse(half_bath_ct == 0, NA, half_bath_rating),
    
    year_built = ifelse(year_built == 0, NA, year_built),
    
    finished_area = ifelse(finished_area == 0, NA, finished_area),
    
    land_sf = ifelse(land_sf == 0, NA, land_sf),
    
    sale_month = ifelse(is.na(sale_date), "none", month(sale_date)), # month
    sale_year = ifelse(is.na(sale_date), "none", year(sale_date)), # year
    sale_wday = ifelse(is.na(sale_date), "none", wday(sale_date)), # day of the week
    sale_week = ifelse(is.na(sale_date), "none", week(sale_date)), # week number (1-52)
    
    # for now 
    sale_year = ifelse(sale_year == "2021" & (sale_month %in% c("9", "12")), "2020", sale_year),

    sale_status = ifelse(is.na(sale_price), "no", "yes"),
    sale_price_group = case_when(
      sale_price <= 100000 ~ "<100k",
      sale_price > 100000 & sale_price <= 150000 ~ "100-150k",
      sale_price > 150000 & sale_price <= 200000 ~"150-200k",
      sale_price > 200000 ~ ">200k",
      is.na(sale_price) ~ "no_sale"),   # several sale price of 0
    
    appealed19 = ifelse(is.na(appealed19), "no", "yes"), 
    appealed20 = ifelse(is.na(appealed20), "no", "yes"),
    appealed21 = ifelse(is.na(appealed21), "no", "yes"),
    
    ) %>% 
  left_join(geo_cleaned, by = "prop_id") # finally, joined with latitude/longitude data
```

# Data Viz

```{r}
housing %>%
  select(appealed19:appealed21) %>% 
  pivot_longer(everything(),
               names_to = "year",
               names_prefix = "appealed",
               values_to = "appealed") %>% 
  ggplot(aes(x = year, fill = appealed)) +
  geom_bar(position = "fill") +
  scale_y_continuous(labels = percent) +
  labs(title = "Property appeal by year",
       subtitle = "Notice 2020",
       y = "Percentage",
       x = "Year",
       fill = "Apealed")
```

```{r}
housing %>%
  select(appealed19:appealed21) %>% 
  pivot_longer(everything(),
               names_to = "year",
               names_prefix = "appealed",
               values_to = "appealed") %>% 
  group_by(year) %>% 
  summarize(n = n(),
            n_appealed = sum(appealed == "yes"),
            pct_appealed = 100 * n_appealed / n)
```

```{r}
library(tidytext)
housing %>% 
  select(nbhd, appealed19:appealed21) %>% 
  pivot_longer(!nbhd,
               names_to = "year",
               names_prefix = "appealed",
               values_to = "appealed") %>% 
  mutate(year = paste0("20", year)) %>% 
  group_by(nbhd, year) %>% 
  summarize(n = n(),
            n_appealed = sum(appealed == "yes"),
            pct_appealed = n_appealed / n) %>% 
  ungroup() %>% 
  group_by(year) %>% 
  slice_max(n = 15, order_by = pct_appealed) %>% 
  mutate(nbhd = reorder_within(nbhd, pct_appealed, year)) %>% 
  ggplot(aes(pct_appealed, nbhd)) +
  geom_col() +
  facet_wrap(~ year, scales = "free") +
  scale_y_reordered() +
  scale_x_continuous(label = percent) +
  labs(x = "% appealed",
       y = "Neighborhood",
       title = "Top 15 neighborhoods with highest property appeal rate")
```

```{r, fig.width=8}
housing %>% 
  select(zip, appealed19:appealed21) %>% 
  pivot_longer(!zip,
               names_to = "year",
               names_prefix = "appealed",
               values_to = "appealed") %>% 
  mutate(year = paste0("20", year)) %>% 
  group_by(zip, year) %>% 
  summarize(n = n(),
            n_appealed = sum(appealed == "yes"),
            pct_appealed = n_appealed / n) %>% 
  ungroup() %>% 
  group_by(year) %>% 
  slice_max(n = 10, order_by = pct_appealed) %>% 
  mutate(zip = reorder_within(zip, pct_appealed, year)) %>% 
  ggplot(aes(pct_appealed, zip)) +
  geom_col() +
  facet_wrap(~ year, scales = "free") +
  scale_y_reordered() +
  scale_x_continuous(label = percent) +
  labs(x = "% appealed",
       y = "Zip Code",
       title = "Top 15 zip codes with highest property appeal rate")
```

```{r, fig.width=10}
housing %>% 
  select(bld_type, appealed19:appealed21) %>% 
  mutate(bld_type = str_remove(bld_type, " Bldgs")) %>% 
  pivot_longer(!bld_type,
               names_to = "year",
               names_prefix = "appealed",
               values_to = "appealed") %>% 
  mutate(year = paste0("20", year)) %>% 
  group_by(bld_type, year) %>% 
  summarize(n = n(),
            n_appealed = sum(appealed == "yes"),
            pct_appealed = n_appealed / n) %>% 
  ungroup() %>% 
  group_by(year) %>% 
  mutate(bld_type = reorder_within(bld_type, pct_appealed, year)) %>% 
  ggplot(aes(pct_appealed, bld_type)) +
  geom_col() +
  facet_wrap(~ year, scales = "free") +
  scale_y_reordered() +
  scale_x_continuous(label = percent) +
  labs(x = "% appealed",
       y = "Building Type",
       title = "Property appealed rate for all building types")
```

```{r, fig.width=9}
housing %>% 
  select(sale_price_group, appealed19:appealed21) %>% 
  pivot_longer(!sale_price_group,
               names_to = "year",
               names_prefix = "appealed",
               values_to = "appealed") %>% 
  mutate(year = paste0("20", year)) %>% 
  group_by(sale_price_group, year) %>% 
  summarize(n = n(),
            n_appealed = sum(appealed == "yes"),
            pct_appealed = n_appealed / n) %>% 
  ungroup() %>% 
  group_by(year) %>% 
  slice_max(n = 10, order_by = pct_appealed) %>% 
  mutate(sale_price_group = reorder_within(sale_price_group, pct_appealed, year)) %>% 
  ggplot(aes(pct_appealed, sale_price_group)) +
  geom_col() +
  facet_wrap(~ year, scales = "free") +
  scale_y_reordered() +
  scale_x_continuous(label = percent) +
  labs(x = "% appealed",
       y = "Sale Price",
       title = "Property appeal rate and sale price")
```

```{r, fig.width=8}
housing %>% 
  select(lat, long, appealed19:appealed21) %>% 
  pivot_longer(contains("appealed"),
               names_to = "year",
               names_prefix = "appealed",
               values_to = "appealed") %>% 
  mutate(year = paste0("20", year)) %>% 
  group_by(lat = round(lat, 4),
           long = round(long, 4),
           year) %>% 
  summarize(n = n(),
            n_appealed = sum(appealed == "yes"),
            pct_appealed = n_appealed / n) %>% 
  ggplot(aes(long, lat, z = pct_appealed)) +
  stat_summary_hex(alpha = 0.8, bins = 70) +
  scale_fill_viridis_c(direction = -1) +
  facet_wrap(~ year) +
  labs(title = "Map of Milwaukee and property appealed rate",
       fill = "% appealed",
       x = "Longitude",
       y = "Latitude")
```

```{r, fig.width=8}
lat_long <- housing %>% 
  select(lat, long, appealed19:appealed21) %>% 
  pivot_longer(contains("appealed"),
               names_to = "year",
               names_prefix = "appealed",
               values_to = "appealed") %>% 
  mutate(year = paste0("20", year)) %>% 
  group_by(lat = round(lat, 3),
           long = round(long, 3),
           year) %>% 
  summarize(n = n(),
            n_appealed = sum(appealed == "yes"),
            pct_appealed = n_appealed / n)

library(ggmap)

map_range <- c(left = min(housing$long, na.rm = TRUE) - 0.02,
               bottom = min(housing$lat, na.rm = TRUE) - 0.02,
               right = max(housing$long, na.rm = TRUE) + 0.02,
               top = max(housing$lat, na.rm = TRUE) + 0.02)

milwaukee_map <- get_stamenmap(map_range, zoom = 12)

milwaukee_map %>% 
  ggmap() +
  geom_point(aes(long, lat, color = pct_appealed),
             alpha = 1,
             data = lat_long) +
  facet_wrap(~ year) +
  scale_color_viridis_c(direction = -1, alpha = 0.7) + 
  labs(title = "Map of Milwaukee and property appealed rate",
       color = "% appealed",
       x = "Longitude",
       y = "Latitude")
```

